#!/usr/bin/env bash
# describe.sh — `harbor describe [<name>]`: everything Harbor knows about one
# project, in one read-only report.
#
# The point is *effective* values, not manifest echo. A project's PHP comes from
# one of three places, its service images from one of four, its ports from a
# file, its routing from nginx — so "what is actually running here?" is a
# question you otherwise answer by opening five files. This answers it, and
# prints the path behind each answer so you can go check.
#
# Read-only: it reports what the other commands would do and changes nothing they
# wouldn't (the CLI shim it probes through is regenerated by every `harbor run`).

_dsc_section() { printf '\n%s%s%s\n' "$_c_blu" "$1" "$_c_reset"; }
_dsc_row()     { printf '  %-20s %s\n' "$1" "${2:--}"; }
_dsc_note()    { printf '  %s%s%s\n' "$_c_dim" "$1" "$_c_reset"; }

# _dsc_pathrow <label> <path> — like _dsc_row, but flags a path that isn't there.
# Generated files (socket, pool conf, vhost) legitimately go missing when Harbor
# is stopped or a project isn't linked, and that absence is the useful bit.
_dsc_pathrow() {
  if [ -e "$2" ]; then _dsc_row "$1" "$2"
  else _dsc_row "$1" "$2  ${_c_ylw}(absent)${_c_reset}"; fi
}

# One PHP call for everything we want out of the runtime, as KEY=VALUE lines.
# Called with the project's SHIM (not brew's php), so the values reported are the
# ones Harbor really applies — xdebug toggle and manifest php_ini included.
_dsc_php_probe() {
  "$1" -d display_errors=0 -r '
$keys = ["memory_limit","max_execution_time","upload_max_filesize","post_max_size",
         "date.timezone","opcache.enable_cli","extension_dir",
         "xdebug.mode","xdebug.start_with_request","xdebug.client_host","xdebug.client_port"];
printf("version=%s\n", PHP_VERSION);
printf("ini_loaded=%s\n", php_ini_loaded_file() ? php_ini_loaded_file() : "-");
printf("ini_scandir=%s\n", PHP_CONFIG_FILE_SCAN_DIR ? PHP_CONFIG_FILE_SCAN_DIR : "-");
$s = php_ini_scanned_files();
$f = $s ? array_filter(array_map("trim", explode(",", $s))) : array();
printf("ini_scanned=%s\n", $f ? implode(" ", array_map("basename", $f)) : "-");
printf("extensions=%d\n", count(get_loaded_extensions()));
foreach ($keys as $k) { $v = ini_get($k); printf("%s=%s\n", $k, ($v === false || $v === "") ? "-" : $v); }
' 2>/dev/null
}

# Exact key lookup in the probe output. Not `grep "^$1="` — the keys contain dots,
# which grep would read as wildcards.
_dsc_probe_get() {
  printf '%s\n' "$_DSC_PROBE" | awk -F= -v k="$1" '$1==k { sub(/^[^=]*=/, ""); print; exit }'
}

# ── sections ────────────────────────────────────────────────────────────────

_dsc_project() {
  local name="$1" dir="$2" mf="$3" framework="$4" vhost extra
  vhost="$HARBOR_NGINX_SITES/$name.$HARBOR_TLD.conf"
  _dsc_section "Project"
  _dsc_row "name" "$name"
  _dsc_row "dir" "$dir"
  _dsc_row "manifest" "$mf"
  local fwsrc="detected — not pinned in the manifest"
  [ -n "$(manifest_get "$mf" framework "")" ] && fwsrc="from the manifest"
  _dsc_row "framework" "$framework  ${_c_dim}$fwsrc${_c_reset}"
  _dsc_row "docroot" "$(link_docroot "$name" "$framework" "$dir")"
  if [ -f "$vhost" ]; then
    _dsc_row "url" "https://$name.$HARBOR_TLD  ${_c_grn}linked${_c_reset}"
  else
    _dsc_row "url" "https://$name.$HARBOR_TLD  ${_c_ylw}NOT linked${_c_reset}  → harbor link $name"
  fi
  extra="$(manifest_list "$mf" domains)"
  [ -n "$extra" ] && _dsc_row "extra domains" "$extra"
  _dsc_pathrow "vhost" "$vhost"
}

_dsc_php() {
  local name="$1" mf="$2" ver src vs cli fpm phpdir shim label pairs
  vs="$(current_php_source "$name")"; ver="${vs%%|*}"; src="${vs#*|}"
  valid_php_version "$ver" || die "unsupported php version '$ver' (have: $HARBOR_PHP_VERSIONS)"
  cli="$(php_cli_bin "$ver")"; fpm="$(php_fpm_bin "$ver")"

  _dsc_section "PHP"
  if [ ! -x "$cli" ]; then
    _dsc_row "pinned" "$ver  ${_c_dim}from $src${_c_reset}"
    _dsc_row "cli" "${_c_red}php@$ver not installed${_c_reset}  → brew install php@$ver"
    return 0
  fi

  # Probe THROUGH the shim `harbor run`/`magento` exec, so what we print is what
  # those commands get. Writing it is the same idempotent side effect cmd_run has.
  phpdir="$(cli_php_pathdir "$ver" "$name")"; shim="$phpdir/php"
  _DSC_PROBE="$(_dsc_php_probe "$shim")"
  [ -n "$_DSC_PROBE" ] || warn "could not run $shim — runtime values below may be blank"

  _dsc_row "version" "$(_dsc_probe_get version)"
  _dsc_row "pinned" "$ver  ${_c_dim}from $src${_c_reset}"
  _dsc_row "cli" "$cli"
  _dsc_row "shim" "$shim  ${_c_dim}what harbor run/magento exec${_c_reset}"
  _dsc_row "php.ini" "$(_dsc_probe_get ini_loaded)"
  _dsc_row "scanned ini" "$(_dsc_probe_get ini_scanned)  ${_c_dim}in $(_dsc_probe_get ini_scandir)${_c_reset}"
  _dsc_row "extensions" "$(_dsc_probe_get extensions) loaded  ${_c_dim}(harbor doctor $name checks the baseline)${_c_reset}"
  local k
  for k in memory_limit max_execution_time upload_max_filesize post_max_size date.timezone; do
    _dsc_row "$k" "$(_dsc_probe_get "$k")"
  done

  pairs="$(manifest_pairs "$mf" php_ini)"
  if [ -n "$pairs" ]; then
    _dsc_row "manifest php_ini" "$(printf '%s' "$pairs" | tr '\n' ' ')"
    _dsc_note "applied to both surfaces — PHP_VALUE in the vhost, -d flags in the shim"
  fi

  # the FPM side
  _dsc_pathrow "fpm pool" "$(php_fpm_conf "$ver")"
  _dsc_pathrow "fpm socket" "$(php_sock "$ver")"
  label="$(php_ld_label "$ver")"
  if launchd_agent_loaded "$label"; then _dsc_row "fpm launchd" "$label  ${_c_grn}loaded${_c_reset}"
  else _dsc_row "fpm launchd" "$label  ${_c_ylw}not loaded${_c_reset}  → harbor start"; fi

  # the terminal's php is a different thing, and the mismatch bites people
  local linked lver
  linked="$(_php_current_formula 2>/dev/null || true)"
  lver="$("$BREW_PREFIX/bin/php" -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null || true)"
  if [ ! -x "$BREW_PREFIX/bin/php" ]; then
    _dsc_row "brew-linked" "${_c_ylw}none${_c_reset}  ${_c_dim}nothing linked — bare \`php\` in a terminal won't run${_c_reset}"
    _dsc_note "Harbor is unaffected. To get one back: harbor php use $ver"
  elif [ -n "$lver" ] && [ "$lver" != "$ver" ]; then
    local tag="${linked:-?}"
    [ "$linked" != "php@$lver" ] && tag="$tag ($lver)"
    _dsc_row "brew-linked" "$tag  ${_c_dim}your plain terminal \`php\` — NOT this project's${_c_reset}"
  fi
}

_dsc_xdebug() {
  local ver="$1" state so dflags
  state="$(xdebug_state)"
  _dsc_section "Xdebug"
  if [ "$state" = on ]; then _dsc_row "toggle" "${_c_grn}on${_c_reset}  ${_c_dim}(global — harbor xdebug off)${_c_reset}"
  else _dsc_row "toggle" "off  ${_c_dim}(harbor xdebug on)${_c_reset}"; fi
  if xdebug_cli_trigger; then
    _dsc_row "cli trigger" "automatic  ${_c_dim}(the shim exports XDEBUG_TRIGGER=1 — no prefix needed)${_c_reset}"
  else
    _dsc_row "cli trigger" "manual  ${_c_dim}(prefix runs with XDEBUG_TRIGGER=1)${_c_reset}"
  fi
  # Three distinct states, and conflating them reads as a contradiction: an
  # xdebug loaded by the version's OWN ini (a conf.d drop-in) is present and
  # working even though there's no xdebug.so at extension_dir — reporting that as
  # "not built" next to "auto-loaded: yes" is just confusing.
  local autoloaded=no
  php_ext_loaded "$(php_cli_bin "$ver")" xdebug && autoloaded=yes
  if so="$(xdebug_so_for "$ver")"; then
    _dsc_row "extension" "$so"
  elif [ "$autoloaded" = yes ]; then
    _dsc_row "extension" "loaded by php@$ver's own ini  ${_c_dim}(no xdebug.so at extension_dir)${_c_reset}"
  else
    _dsc_row "extension" "${_c_ylw}not available for php $ver${_c_reset}  → pecl install xdebug"
  fi
  if [ "$autoloaded" = yes ]; then
    _dsc_row "auto-loaded" "yes  ${_c_dim}(by brew's ini — Harbor only sets xdebug.mode)${_c_reset}"
  else
    _dsc_row "auto-loaded" "no  ${_c_dim}(Harbor adds -d zend_extension when on)${_c_reset}"
  fi
  _dsc_row "mode" "$(_dsc_probe_get xdebug.mode)"
  _dsc_row "client" "$(_dsc_probe_get xdebug.client_host):$(_dsc_probe_get xdebug.client_port)  ${_c_dim}start: $(_dsc_probe_get xdebug.start_with_request)${_c_reset}"
  # xdebug_dflags leads with a space when there's no zend_extension to add.
  dflags="$(xdebug_dflags "$ver" | sed 's/^ *//')"
  _dsc_row "flags" "${dflags:-(none)}"
}

# Per-service line: image (at its real precedence), published port, container
# state, data volume. Docker is consulted once for the whole stack, not per row.
_dsc_services() {
  local name="$1" mf="$2" framework="$3" svcs running="" docker_ok=0 svc img port vol state
  svcs="$(_project_services "$name" "$framework")"
  _dsc_section "Services (Docker)"
  if [ -z "$(_mf_trim "$svcs")" ]; then
    _dsc_row "(none)" "no containers — harbor services add $name <svc>"
    return 0
  fi
  if docker info >/dev/null 2>&1; then
    docker_ok=1
    # `|| true` INSIDE the substitution: a failing assignment RHS takes the whole
    # statement down under set -e, and a project that was never `up`ed is a normal
    # state, not an error.
    running=" $(project_compose "$name" ps --services --status running 2>/dev/null | tr '\n' ' ' || true) "
  fi
  ports_load "$name" 2>/dev/null || true
  for svc in $svcs; do
    img="$(_service_image "$name" "$svc")"
    port=""
    case "$svc" in
      mysql)         port="${DB_PORT-}" ;;
      opensearch)    port="${OPENSEARCH_PORT-}" ;;
      elasticsearch) port="${ELASTIC_PORT-}" ;;
      rabbitmq)      port="${RABBITMQ_PORT-} (ui ${RABBITMQ_UI_PORT-})" ;;
      meilisearch)   port="${MEILI_PORT-}" ;;
    esac
    if [ "$docker_ok" = 0 ]; then state="${_c_dim}docker unreachable${_c_reset}"
    else
      case "$running" in
        *" $svc "*) state="${_c_grn}running${_c_reset}" ;;
        *)          state="${_c_ylw}stopped${_c_reset}" ;;
      esac
    fi
    vol="$(_service_volume "$name" "$svc")"
    _dsc_row "$svc" "$img"
    printf '  %-20s %s\n' "" "127.0.0.1:${port:-?}  $state${vol:+  vol: $vol}"
  done
  _dsc_pathrow "compose" "$(project_compose_file "$name")"
  # Redis and mail are shared singletons, never per-project — say so here so the
  # absence of a redis row doesn't read as "this project has no Redis".
  if [ -n "${REDIS_DB_CACHE-}" ]; then
    _dsc_row "redis (shared)" "127.0.0.1:6379  db $REDIS_DB_CACHE cache / $REDIS_DB_PAGE page / $REDIS_DB_SESSION session"
  fi
  _dsc_row "mail (shared)" "smtp 127.0.0.1:1025   ui http://localhost:8025"
}

_dsc_database() {
  local name="$1" ident
  project_has_service "$name" mysql || return 0
  ident="$(db_ident "$name")"
  _dsc_section "Database"
  if ports_load "$name" 2>/dev/null; then
    _dsc_row "dsn" "127.0.0.1:$DB_PORT"
  else
    _dsc_row "dsn" "${_c_ylw}no port allocated${_c_reset}  → harbor init $name"
  fi
  _dsc_row "db / user / pass" "$ident / $ident / $ident"
  _dsc_pathrow "connection.env" "$(project_harbor_dir "$name")/connection.env"
  _dsc_row "backups" "$HARBOR_BACKUPS/$name"
}

_dsc_multistore() {
  local name="$1" mf="$2" mode w s
  mode="$(manifest_get "$mf" multistore.mode none)"
  if [ -z "$mode" ] || [ "$mode" = none ]; then return 0; fi
  _dsc_section "Multi-store (Magento)"
  _dsc_row "mode" "$mode"
  w="$(_store_pairs "$name" websites)"
  s="$(_store_pairs "$name" stores)"
  if [ -n "$w" ]; then
    _dsc_row "scope" "website  ${_c_dim}(MAGE_RUN_TYPE=website)${_c_reset}"
    printf '%s\n' "$w" | sed 's/^/      /'
  fi
  if [ -n "$s" ]; then
    _dsc_row "scope" "store view  ${_c_dim}(MAGE_RUN_TYPE=store)${_c_reset}"
    printf '%s\n' "$s" | sed 's/^/      /'
  fi
  if [ "$mode" = path ]; then
    _dsc_note "path mode needs web/url/use_store=0 AND web/url/redirect_to_base=0"
  fi
}

_dsc_extras() {
  local name="$1" mf="$2" dir="$3" hdir node tools t hooks scripts remote
  hdir="$(project_harbor_dir "$name")"
  node="$(manifest_get "$mf" node "")"
  [ -z "$node" ] && [ -f "$dir/.nvmrc" ] && node="$(tr -d ' \n\r' < "$dir/.nvmrc") (.nvmrc)"
  tools="$(tools_declared "$mf" | tr '\n' ' ')"
  remote="$(manifest_get "$mf" remote.host "")"
  # Only hook dirs that actually hold an EXECUTABLE file count — a dir full of
  # non-executable `.sample`s is exactly the state that reads as "I have hooks"
  # and silently runs none.
  hooks=""; local n
  for t in pre-import.d post-import.d; do
    [ -d "$hdir/hooks/$t" ] || continue
    n="$(find "$hdir/hooks/$t" -type f -perm -u+x 2>/dev/null | wc -l | tr -d ' ')"
    if [ "${n:-0}" -gt 0 ]; then hooks="${hooks:+$hooks }$t($n)"; fi
  done
  scripts=""
  [ -d "$hdir/scripts" ] && scripts="$(find "$hdir/scripts" -type f -perm -u+x 2>/dev/null | wc -l | tr -d ' ') executable"

  # Nothing to say is a valid outcome — don't print an empty section.
  [ -z "$node$tools$remote$hooks" ] && [ -z "$scripts" ] && return 0
  _dsc_section "Extras"
  [ -n "$node" ] && _dsc_row "node" "$node"
  if [ -n "$(_mf_trim "$tools")" ]; then
    _dsc_row "tools" "$tools ${_c_dim}(containerized — shims in .harbor/bin/)${_c_reset}"
  fi
  [ -n "$(_mf_trim "$hooks")" ] && _dsc_row "import hooks" "$hooks"
  [ -n "$scripts" ] && _dsc_row "scripts" "$scripts  ${_c_dim}(.harbor/scripts — first on PATH for run/shell)${_c_reset}"
  if [ -n "$remote" ]; then
    _dsc_row "remote" "$remote  ${_c_dim}(harbor db pull / media pull)${_c_reset}"
  fi
}

# harbor describe [<name>]
cmd_describe() {
  # `describe` has no positionals of its own, so an argument that names no
  # project is a typo — say THAT. resolve_project deliberately leaves such an
  # argument alone (it's how `harbor db backup reporting` dumps a database), and
  # its generic "not inside one" would be the wrong diagnosis here.
  if [ "$#" -ge 1 ] && [ -n "${1-}" ] && [ ! -d "$(project_dir "$1")" ]; then
    die "no such project '$1' → harbor list"
  fi
  resolve_project "${1-}" "harbor describe [<name>]"
  [ "$_RP_SHIFT" = 1 ] && shift
  [ "$#" -eq 0 ] || usage_die describe "harbor describe [<name>]"
  local name="$_RP_NAME" dir mf framework ver
  dir="$(project_dir "$name")"
  mf="$(manifest_path "$name")"
  [ -f "$mf" ] || die "no manifest for '$name' ($mf) → harbor init $name --existing"
  framework="$(manifest_get "$mf" framework "$(link_detect_framework "$dir")")"

  _dsc_project "$name" "$dir" "$mf" "$framework"
  _dsc_php "$name" "$mf"
  ver="$(current_php_source "$name")"; ver="${ver%%|*}"
  [ -x "$(php_cli_bin "$ver")" ] && _dsc_xdebug "$ver"
  _dsc_services "$name" "$mf" "$framework"
  _dsc_database "$name"
  _dsc_multistore "$name" "$mf"
  _dsc_extras "$name" "$mf" "$dir"
  printf '\n'
}
