#!/usr/bin/env bash
# remote.sh — pull DB / media from a remote host (manifest `remote:` block).

# _shq <string> — single-quote a string for safe embedding in a shell command,
# escaping any embedded single quotes ('->'\''). Lets an arbitrary password/user/
# db name reach the remote shell without breaking its quoting or being injectable.
_shq() { local s=$1; s=${s//\'/\'\\\'\'}; printf "'%s'" "$s"; }

# _remote_protect <name> — if .harbor/remote.env exists, make sure it's gitignored
# (it may hold host/user/db as well as the password). Idempotent; call before
# reading any remote field so a project predating the template line stays safe.
# (_ensure_gitignored lives in common.sh — a generic utility used by init too.)
_remote_protect() {
  local rf; rf="$(project_harbor_dir "$1")/remote.env"
  [ -f "$rf" ] && _ensure_gitignored "$1" "remote.env"
}

# _remote_field <name> <ENVKEY> <manifest_subkey> — resolve one remote connection
# field, echoing it. Order: environment variable $ENVKEY → the same key in the
# gitignored .harbor/remote.env → manifest `remote.<subkey>`. This lets prod
# connection details (host, db, user, db_host, media) be kept OUT of the
# committable manifest entirely — put them in .harbor/remote.env instead — while
# the manifest keys still work as a shareable fallback.
_remote_field() {
  local name="$1" envkey="$2" mkey="$3" v rf
  v="${!envkey:-}"                       # 1. exported env var wins
  if [ -n "$v" ]; then printf '%s' "$v"; return 0; fi
  rf="$(project_harbor_dir "$name")/remote.env"
  if [ -f "$rf" ]; then                  # 2. gitignored remote.env
    # `|| v=""` guards a failing statement in the sourced file from aborting the
    # caller under set -e (stderr suppressed → silent). See _remote_db_password.
    v="$( . "$rf" 2>/dev/null; printf '%s' "${!envkey:-}" )" || v=""
    if [ -n "$v" ]; then printf '%s' "$v"; return 0; fi
  fi
  manifest_get "$(manifest_path "$name")" "remote.$mkey" ""   # 3. manifest
}

# _remote_db_password <name> <user> <host> — resolve the password for the remote
# MySQL user into $_RPASS. Order: $HARBOR_REMOTE_DB_PASSWORD env → the same key in
# .harbor/remote.env (gitignored, never generated by Harbor) → interactive silent
# prompt. The password is NEVER read from the manifest. Sets a global (not stdout)
# so a `die` here aborts the command instead of dying only inside a $(...) subshell.
_remote_db_password() {
  local name="$1" user="$2" host="$3" rf
  _RPASS=""
  rf="$(project_harbor_dir "$name")/remote.env"
  if [ -n "${HARBOR_REMOTE_DB_PASSWORD:-}" ]; then
    _RPASS="$HARBOR_REMOTE_DB_PASSWORD"; return 0
  fi
  if [ -f "$rf" ]; then
    # One name for both surfaces: the file key is HARBOR_REMOTE_DB_PASSWORD, same
    # as the env var. Sourced (like connection.env) so the value may be computed;
    # `|| _RPASS=""` guards a failing statement in the file, which would otherwise
    # abort db_pull under set -e — silently, since stderr is suppressed — instead
    # of falling through to the prompt.
    _RPASS="$( . "$rf" 2>/dev/null; printf '%s' "${HARBOR_REMOTE_DB_PASSWORD:-}" )" || _RPASS=""
    [ -n "$_RPASS" ] && return 0
  fi
  # Not stored anywhere → ask. Needs a terminal; read from /dev/tty (not stdin,
  # which may be redirected). Probe by actually opening it — `[ -r /dev/tty ]`
  # can report readable on a controlling terminal that still fails to open
  # ("Device not configured"), which would spew errors and a bogus "empty
  # password" instead of this actionable hint.
  if ! { : </dev/tty; } 2>/dev/null; then
    die "no password for remote MySQL user '$user' → set HARBOR_REMOTE_DB_PASSWORD (export it, or add it to $rf), or run interactively"
  fi
  printf 'Password for remote MySQL user %s@%s: ' "$user" "${host##*@}" >/dev/tty
  IFS= read -r -s _RPASS </dev/tty
  printf '\n' >/dev/tty
  [ -n "$_RPASS" ] || die "empty password — aborting"
  return 0
}

# _remote_dump <host> <rdb> [user] [pass] [db_host] — stream `mysqldump | gzip`
# from the remote to stdout. With a user, auth goes through MYSQL_PWD set INSIDE
# the ssh script (fed on stdin), so the password never appears in any process's
# argv — not locally, not on the remote. Without one, we rely on the remote's own
# ~/.my.cnf / socket auth (original behavior). A db_host adds `-h <host>` so the
# dump connects the same way the app does (TCP to 127.0.0.1) instead of over the
# socket — MySQL treats the socket as `@localhost`, which a TCP-granted app user
# usually can't match. `set -o pipefail` on the remote so a failed mysqldump
# propagates instead of being masked by gzip's exit 0.
_remote_dump() {
  local host="$1" rdb="$2" user="${3-}" pass="${4-}" dbhost="${5-}"
  # Every value is single-quoted with _shq before it enters the remote command,
  # so an arbitrary db name / user / host can't break quoting or inject.
  local args="--single-transaction --no-tablespaces --routines --triggers"
  [ -n "$dbhost" ] && args="$args -h $(_shq "$dbhost")"
  [ -n "$user" ] && args="$args -u $(_shq "$user")"
  # A password line is emitted only with a user; MYSQL_PWD is set in-script so it
  # never lands in any process's argv. No user → defer to the remote's own auth.
  local pwline=""
  [ -n "$user" ] && pwline="export MYSQL_PWD=$(_shq "$pass")"
  # BOTH branches run through `bash -s` (script fed on stdin), NOT the login
  # shell: `set -o pipefail` must be honored so a failed mysqldump propagates
  # instead of being masked by gzip's exit 0, and the login shell isn't
  # guaranteed to be bash (dash/csh/tcsh would choke on `set -o pipefail`).
  # Expansions here are intentionally CLIENT-side: _shq runs locally and embeds
  # the safely quoted values into the script the remote runs (no server-side _shq).
  # shellcheck disable=SC2087
  ssh "$host" 'bash -s' <<EOF
set -o pipefail
$pwline
mysqldump $args $(_shq "$rdb") | gzip
EOF
}

# harbor db pull [<name>] [--reconfigure ...]  (extra opts pass through to import)
db_pull() {
  resolve_project "${1-}" "harbor db pull [<name>] [import opts...]"
  [ "$_RP_SHIFT" = 1 ] && shift; local name="$_RP_NAME"
  local host rdb ruser rpass="" rdbhost tmp
  _remote_protect "$name"
  host="$(_remote_field "$name" HARBOR_REMOTE_HOST host)"
  rdb="$(_remote_field "$name" HARBOR_REMOTE_DB db)"
  [ -n "$host" ] && [ -n "$rdb" ] || die "set the remote host and db — either 'remote: { host, db }' in the manifest, or HARBOR_REMOTE_HOST / HARBOR_REMOTE_DB in .harbor/remote.env (keeps prod details out of git)"
  ruser="$(_remote_field "$name" HARBOR_REMOTE_USER user)"
  rdbhost="$(_remote_field "$name" HARBOR_REMOTE_DB_HOST db_host)"
  # A remote user opts into Harbor-supplied auth; without it we defer to the
  # remote's own ~/.my.cnf / socket auth exactly as before. A password-based user
  # is almost always granted for TCP (127.0.0.1 / %), not the socket's @localhost,
  # so default the dump to connect over 127.0.0.1 — overridable, incl. `localhost`
  # to force the socket back.
  [ -n "$ruser" ] && [ -z "$rdbhost" ] && rdbhost="127.0.0.1"
  _db_load "$name"; _db_up_check "$name"
  need_cmd ssh
  if [ -n "$ruser" ]; then
    _remote_db_password "$name" "$ruser" "$host"; rpass="$_RPASS"
  fi
  # BSD mktemp only substitutes TRAILING X's, so the template's XXXXXX must be
  # last; rename to .sql.gz afterward because db_import decompresses by extension.
  tmp="$(mktemp "${TMPDIR:-/tmp}/harbor-pull.XXXXXX")" || die "mktemp failed"
  mv "$tmp" "$tmp.sql.gz" || { rm -f "$tmp"; die "could not prepare temp file"; }
  tmp="$tmp.sql.gz"
  log "pulling '$rdb' from $host${ruser:+ as MySQL user '$ruser'}${rdbhost:+ via $rdbhost} (mysqldump over ssh)"
  _remote_dump "$host" "$rdb" "$ruser" "$rpass" "$rdbhost" > "$tmp" \
    || { rm -f "$tmp"; die "remote dump failed — is $host reachable over ssh, and does it have mysqldump? Then check the db name '$rdb' and MySQL access${ruser:+ for user '$ruser' (connected via ${rdbhost:-socket}; wrong password, or the user is granted for a different host? override with remote.db_host, e.g. 127.0.0.1 or localhost)}"; }
  db_import "$name" "$tmp" "$(db_ident "$name")" "$@"
  rm -f "$tmp"
  ok "db pull complete for $name"
}

# harbor media pull [<name>]
media_pull() {
  resolve_project "${1-}" "harbor media pull [<name>]"
  [ "$_RP_SHIFT" = 1 ] && shift; local name="$_RP_NAME"
  local host media dir framework dest
  _remote_protect "$name"
  host="$(_remote_field "$name" HARBOR_REMOTE_HOST host)"
  media="$(_remote_field "$name" HARBOR_REMOTE_MEDIA media)"
  [ -n "$host" ] && [ -n "$media" ] || die "set the remote host and media path — either 'remote: { host, media: /path }' in the manifest, or HARBOR_REMOTE_HOST / HARBOR_REMOTE_MEDIA in .harbor/remote.env"
  need_cmd rsync
  dir="$(project_dir "$name")"; framework="$(_install_framework "$name")"
  case "$framework" in
    magento) dest="$dir/pub/media" ;;
    laravel) dest="$dir/storage/app" ;;
    *)       dest="$dir/media" ;;
  esac
  mkdir -p "$dest"
  log "rsync $host:$media/ -> $dest/"
  rsync -az --delete --exclude 'cache/**' --exclude '*/cache/**' "$host:$media/" "$dest/"
  ok "media pull complete for $name"
}

cmd_media() {
  [ "${1-}" = "pull" ] || usage_die media "harbor media pull [<name>]"
  shift; media_pull "$@"
}
